name: Matikkapipeline
on:
  push:
    branches: [ main ]
defaults:
  run:
    working-directory: ./MathWorkshop
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - run: dotnet restore
      name: Restore
    - run: dotnet build
      name: Build
    - run: dotnet test
      name: Unit tests
